version: "3.9"
services:
  gomoku-db:
    container_name: gomoku-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  gomoku-service1:
    container_name: gomoku-service1
    depends_on:
      - gomoku-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - DB_URL=jdbc:postgresql://gomoku-db:5432/postgres?user=postgres&password=postgres
    expose:
      - "8081:8080"
  gomoku-service2:
    container_name: gomoku-service2
    depends_on:
      - gomoku-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - DB_URL=jdbc:postgresql://gomoku-db:5432/postgres?user=postgres&password=postgres
    expose:
      - "8082:8080"
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-nginx
    ports:
      - "8000:80"
    volumes:
      - ./dockerfiles/nginx:/etc/nginx
    depends_on:
      - gomoku-service1
      - gomoku-service2
