version: "3.9"
services:
  gomoku-db:
    container_name: gomoku-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=master
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  gomoku-service-1:
    container_name: gomoku-service-1
    depends_on:
      - gomoku-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - DB_URL=jdbc:postgresql://gomoku-db:5432/postgres?user=postgres&password=master
    ports:
      - "8081:8081"

  gomoku-service-2:
    container_name: gomoku-service-2
    depends_on:
      - gomoku-service-1
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - DB_URL=jdbc:postgresql://gomoku-db:5432/postgres?user=postgres&password=master
    ports:
      - "8082:8082"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./dockerfiles/nginx:/etc/nginx
    depends_on:
      - gomoku-service-1
      - gomoku-service-2

  # Just a machine running ubuntu, with 'dig' installed so that we can observe the docker compose environment.
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-ubuntu
    tty: true